### ISSUE TITLE
comments

### ISSUE THREAD

**Issue by yatli** [thautwarm/daily-coding-playground#1]
General comments regarding C# programming. :)

**Comment by yatli** [comment]
https://github.com/thautwarm/cache/blob/2754d9fef20f9dddfdc1417d218a891a98ec1a35/daily/CSharpProj/DataGen.cs#L22

See ```Enumerable.Range```.

**Comment by yatli** [comment]
https://github.com/thautwarm/cache/blob/2754d9fef20f9dddfdc1417d218a891a98ec1a35/daily/CSharpProj/DataGen.cs#L49

In C#7 we have `ValueTuple` which is a value type, allocated on stack, generally faster.

**Comment by yatli** [comment]
https://github.com/thautwarm/cache/blob/2754d9fef20f9dddfdc1417d218a891a98ec1a35/daily/CSharpProj/DataGen.cs#L48

In numerical scenarios, arrays are generally faster than lists (plus you can use ```fixed(double* p = arr)``` and throw it into other runtimes

**Comment by yatli** [comment]
https://github.com/thautwarm/cache/blob/2754d9fef20f9dddfdc1417d218a891a98ec1a35/daily/CSharpProj/Genetic.cs#L34

```rnd.Next(0, 2)```

Also I'm curious about the performance numbers comparing lists, arrays, and lazy enumerables. Got time to test drive? :)

**Comment by thautwarm** [comment]
Dear Yatli, thank you for your reviewing my codes.
Yesterday I was just to complete my homework as fast as I can, and then poured these dirty codes into my GitHub repo... 
As you can see that I named this repo as `cache`...  They're just  some caches...
There is no C# 7.0 in the computer in our college, so there're no `ValueTuple` and so on...   
What's more, I appreciate a lot that you told me some APIs like `rnd.Next(begin)` and `Enumerable.Range`...
